---
name: linting

on:
  push: {}
  pull_request: {}


jobs:
  terraform fmt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
      - name: Terraform Format
        run: terraform fmt -check -diff -recursive .
